spring:
  application:
    name: cloud-gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://localhost:8083/
          predicates:
          - Path=/products/**

server:
  port: 8080

